name: Build Godot Project

on:
  push:
    branches:
      - main  # Oder dein Entwicklungsbranch

jobs:
  build:
    runs-on: ubuntu-latest  # Kann auch windows-latest sein, falls nötig
    permissions: write-all
    name: Build Game
    
    steps:
      - name: Repository klonen
        uses: actions/checkout@v4

      - name: Godot installieren und Bauen
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true

      - name: Exportierte Dateien als Artefakt speichern
        uses: actions/upload-artifact@v4
        with:
          name: godot-build
          path: |
              Build/
              logs/
          retention-days: 30
          
      - name: create release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*